=== Vaibhav-Sonkusare/MTech_Labs/WebDev/lab5/department.dtd
<!ELEMENT department (dept_name, hod_name, faculty_list, student_list)>
<!ELEMENT dept_name (#PCDATA)>
<!ELEMENT hod_name (#PCDATA)>

<!ELEMENT faculty_list (faculty+)>
<!ELEMENT faculty (name, designation, email)>
<!ATTLIST faculty id CDATA #REQUIRED>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT student_list (student+)>
<!ELEMENT student (name, semester, cgpa)>
<!ATTLIST student roll CDATA #REQUIRED>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT cgpa (#PCDATA)>

<!ELEMENT name (#PCDATA)>

=== Vaibhav-Sonkusare/MTech_Labs/WebDev/lab5/department.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE department SYSTEM "department.dtd">
<department>
	<dept_name>d</dept_name>
	<hod_name>gh</hod_name>
	<faculty_list>
		<faculty id="fds">
			<name>fsd</name>
			<designation>dsca</designation>
			<email>fds@f.c</email>
		</faculty>
	</faculty_list>
	<student_list>
		<student roll="sfdc">
			<name>ferwa</name>
			<semester>6</semester>
			<cgpa>5</cgpa>
		</student>
	</student_list>
</department>
